### ISSUE TITLE
Fails with invalid xml in commit messages

### ISSUE THREAD

**Issue by shannoncornish** [dogeth/ccnet.git.plugin#2]
Our most recent git commit message contained an ampersand character which has caused our build to brake with the following exception.

---

ThoughtWorks.CruiseControl.Core.CruiseControlException: History Parsing Failed ---> System.InvalidOperationException: There is an error in XML document (29, 316). ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 29, position 316. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.Throw(String res, String arg) at System.Xml.XmlTextReaderImpl.ParseEntityName() at System.Xml.XmlTextReaderImpl.ParseEntityReference() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlTextReader.Read() at System.Xml.XmlReader.ReadString() at System.Xml.XmlTextReader.ReadString() at System.Xml.XmlReader.ReadElementString() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModificationArray.Read2_Modification(Boolean isNullable, Boolean checkType) at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderModificationArray.Read3_ArrayOfModification() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at ThoughtWorks.CruiseControl.Core.Sourcecontrol.gitHistoryParser.Parse(TextReader history, DateTime from, DateTime to) --- End of inner exception stack trace --- at ThoughtWorks.CruiseControl.Core.Sourcecontrol.gitHistoryParser.Parse(TextReader history, DateTime from, DateTime to) at ThoughtWorks.CruiseControl.Core.Sourcecontrol.ProcessSourceControl.ParseModifications(ProcessResult result, DateTime from, DateTime to) at ThoughtWorks.CruiseControl.Core.Sourcecontrol.git.GetModifications(IIntegrationResult from, IIntegrationResult to) at ThoughtWorks.CruiseControl.Core.Sourcecontrol.QuietPeriod.GetModifications(ISourceControl sourceControl, IIntegrationResult lastBuild, IIntegrationResult thisBuild) at ThoughtWorks.CruiseControl.Core.IntegrationRunner.GetModifications(IIntegrationResult from, IIntegrationResult to) at ThoughtWorks.CruiseControl.Core.IntegrationRunner.Integrate(IntegrationRequest request)

**Comment by dogeth** [comment]
Shannon has fixed this issue, and I've included his fork in the source.  Thanks Shannon!
