### ISSUE TITLE
History Parsing Failed 

### ISSUE THREAD

**Issue by uShip** [dogeth/ccnet.git.plugin#3]
Hi Dogeth,

I've included the plugin in CruiseControl v1.4.4 on a Win Server 2003, but the service won't complete the initial pull/fetch operation. It does however create an empty repository in the target folder so I know it's understanding the working directory path settings. Here's my ccnet.config:

```
<sourcecontrol type="git">
  <branch>master</branch>
  <repository>c:\repository_git_test\db</repository>
  <autoGetSource>true</autoGetSource>
  <executable>git</executable>
  <workingDirectory>c:\gitbuild2\uship2005</workingDirectory>
</sourcecontrol>
```

And here is the error I am getting in the XML log file:

<exception>
- <![CDATA[ ThoughtWorks.CruiseControl.Core.CruiseControlException: History Parsing Failed ---> System.InvalidOperationException: There is an error in XML document (1579, 270). ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 1579, position 270.

Thank you for your help!
Adrian

**Comment by dnauck** [comment]
You may want to try CruiseControl.NET 1.5 with an improved Git plugin[1] based on this one here.

Daniel

[1] http://confluence.public.thoughtworks.org/display/CCNET/Git+Source+Control+Block

**Comment by uShip** [comment]
Thank you for the info! Any idea when they are releasing?

**Comment by dnauck** [comment]
It will take a while until we release ccnet 1.5, but can you can test the latest build: http://ccnetlive.thoughtworks.com/CCNet-builds/1.5.0/

**Comment by dogeth** [comment]
Hi Adrian,

Sorry for the delay in replying, no email notification and I hardly ever check the site anymore.

I suggest that you do as Daniel says, get on board with CruiseControl.NET 1.5.  This has a git source provider built in, which I've reviewed and like the look of.  As soon as it has released we will be moving to it and this little side project of mine will "retire".

**Comment by uShip** [comment]
Hi Dogeth,

I saw CC 1.5 has been released. Does it live up to your expectations concerning GIT? I'm really eager to get started using GIT and CC and want to make sure it's fully supported. Thank you for your help!
